import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer } from 'react-toastify';
import ReactQueryProviders from '@/react-query-provider';
import { ReactNode } from 'react';
import UserDehydrate from '@/dehydrate-components/user-dehydrate.component';
import Footer from '@/footer';
import Navigation from '@/navigation';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} flex min-h-screen flex-col antialiased`}
            >
                <Navigation />
                <ReactQueryProviders>
                    <UserDehydrate>
                        <main>{children}</main>
                    </UserDehydrate>
                </ReactQueryProviders>

                <ToastContainer position={'bottom-center'} theme={'dark'} />
                <Footer />
            </body>
        </html>
    );
}
