import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer } from 'react-toastify';
import ReactQueryProviders from '@/react-query-provider';
import { ReactNode } from 'react';
import UserDehydrate from '@/dehydrate-components/user-dehydrate.component';
import NavigationBar from '@/navigation';
import { isAuthenticationComplete } from '@/(presentation)/shared/helpers/authentication.helper';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

const NAV_ITEMS = [
    { name: '전적검색', href: '/stats' },
    { name: '무기분석', href: '/weapons' },
    { name: '맵분석', href: '/maps' },
    { name: '전략', href: '/strategies' },
];

export default async function RootLayout({
    children,
}: Readonly<{
    children: ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} h-screen antialiased`}
            >
                <NavigationBar>
                    <NavigationBar.Container>
                        <NavigationBar.Logo />
                        <NavigationBar.ItemNavWrapper>
                            {NAV_ITEMS.map(item => {
                                return (
                                    <NavigationBar.Item
                                        href={item.href}
                                        key={item.href}
                                    >
                                        {item.name}
                                    </NavigationBar.Item>
                                );
                            })}
                        </NavigationBar.ItemNavWrapper>
                    </NavigationBar.Container>

                    <NavigationBar.Container>
                        <NavigationBar.OpenSearch />
                        {(await isAuthenticationComplete()) ? (
                            <NavigationBar.MyPage />
                        ) : (
                            <NavigationBar.Login />
                        )}
                    </NavigationBar.Container>
                </NavigationBar>

                <ReactQueryProviders>
                    <UserDehydrate>{children}</UserDehydrate>
                </ReactQueryProviders>
                <ToastContainer position={'bottom-center'} theme={'dark'} />
            </body>
        </html>
    );
}
